# This workflow builds the full Java project using Maven.
# The webapp is not included.
name: Build Imodec with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ['11']  # Add (java) 8 when ready for it

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn -B package -Dskip.installnodenpm -Dskip.npm --file pom.xml